[pytest]
# Корневая папка проекта
testpaths = tests
# Игнорировать предупреждения
filterwarnings = ignore::DeprecationWarning
# Использовать asyncio для асинхронных тестов
asyncio_mode = auto
# Пакеты, которые нужно включать в поиск тестов
python_files = test_*.py
python_functions = test_*
