volumes:
  pg_data:

services:
  db:
    image: postgres:17-alpine
    env_file: ../.env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 10s
      retries: 5

  rabbit:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

  backend:
    image: python5152plus/tables_booking_system
    env_file: ../.env
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
      rabbit:
        condition: service_started

  flower:
    image: mher/flower
    env_file: ../.env
    command: celery --broker=${CELERY_BROKER_URL} flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - rabbit
