"""...

Revision ID: 068c10945ebb
Revises: 0775bac0a603
Create Date: 2025-09-21 02:59:43.601418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068c10945ebb'
down_revision = '0775bac0a603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
