"""empty message

Revision ID: 41e5d051ae2f
Revises: de77774d20bd
Create Date: 2025-10-07 19:43:37.444342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e5d051ae2f'
down_revision = 'de77774d20bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.Column('guests_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('guests_number >= 1', name='check_guests_positive'),
    sa.CheckConstraint('status IN (0, 1, 2)', name='check_booking_status_valid'),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_cafe_id'), ['cafe_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_user_id'), ['user_id'], unique=False)

    op.create_table('booking_dish',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dish_id'], ['dishe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('booking_id', 'dish_id')
    )
    op.create_table('booking_slot',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['time_slot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('booking_id', 'slot_id')
    )
    op.create_table('booking_table',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('booking_id', 'table_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_table')
    op.drop_table('booking_slot')
    op.drop_table('booking_dish')
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_user_id'))
        batch_op.drop_index(batch_op.f('ix_booking_cafe_id'))

    op.drop_table('booking')
    # ### end Alembic commands ###
