"""Fixed models

Revision ID: 54c02ece07e7
Revises: 19b911fd58c4
Create Date: 2025-09-22 19:10:22.887432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54c02ece07e7'
down_revision = '19b911fd58c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
