"""empty message

Revision ID: a3e8c7aa1591
Revises: aa2532f938d2
Create Date: 2025-10-07 21:47:01.231078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3e8c7aa1591'
down_revision = 'aa2532f938d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
