"""empty message

Revision ID: b73b41e10772
Revises:
Create Date: 2025-09-27 16:10:37.905996

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = 'b73b41e10772'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'cafe',
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('address', sa.String(length=256), nullable=False),
        sa.Column('phone', sa.String(length=15), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('photo', sa.Text(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'user',
        sa.Column('username', sa.String(length=255), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password', sa.String(length=128), nullable=False),
        sa.Column('is_superuser', sa.Boolean(), nullable=False),
        sa.Column('phone', sa.String(length=20), nullable=False),
        sa.Column('tg_id', sa.String(length=50), nullable=True),
        sa.Column(
            'role',
            sa.Enum('ADMIN', 'MANAGER', 'USER', name='user_role_enum'),
            nullable=False,
        ),
        sa.Column(
            'last_used',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('phone'),
        sa.UniqueConstraint('tg_id'),
    )
    op.create_table(
        'action',
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('cafe_id', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_action_cafe_id'), ['cafe_id'], unique=False
        )

    op.create_table(
        'cafe_manager',
        sa.Column('cafe_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['cafe_id'],
            ['cafe.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('cafe_id', 'user_id'),
    )
    op.create_table(
        'dishe',
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('description', sa.String(length=600), nullable=False),
        sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('photo', sa.String(), nullable=True),
        sa.Column('cafe_id', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('dishe', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_dishe_cafe_id'), ['cafe_id'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_dishe_name'), ['name'], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dishe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dishe_name'))
        batch_op.drop_index(batch_op.f('ix_dishe_cafe_id'))

    op.drop_table('dishe')
    op.drop_table('cafe_manager')
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_cafe_id'))

    op.drop_table('action')
    op.drop_table('user')
    op.drop_table('cafe')
    # ### end Alembic commands ###
