"""empty message

Revision ID: de77774d20bd
Revises: 
Create Date: 2025-10-05 22:48:12.526185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de77774d20bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cafe',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'address', name='uix_name_address')
    )
    op.create_table('user',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'manager', 'user', name='user_role_enum'), nullable=False),
    sa.Column('last_used', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('action',
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_cafe_id'), ['cafe_id'], unique=False)

    op.create_table('cafe_manager',
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('cafe_id', 'user_id')
    )
    op.create_table('dishe',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=600), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dishe', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dishe_cafe_id'), ['cafe_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dishe_name'), ['name'], unique=False)

    op.create_table('table',
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.Column('seats_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('seats_number <= 12', name='check_max_seats'),
    sa.CheckConstraint('seats_number >= 1', name='check_min_seats'),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_table_cafe_id'), ['cafe_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_table_seats_number'), ['seats_number'], unique=False)

    op.create_table('time_slot',
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('start_time < end_time', name='ck_slot_start_before_end'),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cafe_id', 'date', 'start_time', 'end_time', name='uq_cafe_date_time_window')
    )
    with op.batch_alter_table('time_slot', schema=None) as batch_op:
        batch_op.create_index('ix_slot_cafe_date_start', ['cafe_id', 'date', 'start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_slot_cafe_id'), ['cafe_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_slot_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_slot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_slot_date'))
        batch_op.drop_index(batch_op.f('ix_time_slot_cafe_id'))
        batch_op.drop_index('ix_slot_cafe_date_start')

    op.drop_table('time_slot')
    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_table_seats_number'))
        batch_op.drop_index(batch_op.f('ix_table_cafe_id'))

    op.drop_table('table')
    with op.batch_alter_table('dishe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dishe_name'))
        batch_op.drop_index(batch_op.f('ix_dishe_cafe_id'))

    op.drop_table('dishe')
    op.drop_table('cafe_manager')
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_cafe_id'))

    op.drop_table('action')
    op.drop_table('user')
    op.drop_table('cafe')
    # ### end Alembic commands ###
