# -------------------
# Build stage
# -------------------
FROM python:3.11-alpine AS build # noqa

# Системные зависимости для сборки пакетов
RUN apk add --no-cache build-base libffi-dev postgresql-dev openssl-dev

WORKDIR /app

# Копируем только requirements
COPY ../requirements.txt .

# Собираем wheel-пакеты
RUN pip wheel --no-cache-dir -r requirements.txt -w /wheels

# -------------------
# Final stage
# -------------------
FROM python:3.11-alpine

# Системные зависимости для работы
RUN apk add --no-cache libffi postgresql-libs openssl

WORKDIR /app

# Устанавливаем зависимости из wheel
COPY --from=build /wheels /wheels
RUN pip install --no-cache-dir /wheels/*

# ВАЖНО: устанавливаем asyncpg отдельно
RUN pip install --no-cache-dir asyncpg

# Копируем исходники приложения
COPY ../src ./src
COPY ../alembic ./alembic
COPY ../alembic.ini .
COPY ../.env .

# Пробрасываем порт для uvicorn
EXPOSE 8000

# Запуск приложения
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
