# -------------------
# Build stage
# -------------------
FROM python:3.11-alpine AS build

RUN apk add --no-cache build-base libffi-dev postgresql-dev openssl-dev

WORKDIR /app

# Копируем только requirements
COPY requirements.txt .

RUN pip wheel --no-cache-dir -r requirements.txt -w /wheels

# -------------------
# Final stage
# -------------------
FROM python:3.11-alpine

RUN apk add --no-cache libffi postgresql-libs openssl

WORKDIR /app

COPY --from=build /wheels /wheels
RUN pip install --no-cache-dir /wheels/*
RUN pip install --no-cache-dir asyncpg

# Копируем исходники приложения
COPY src ./src
COPY alembic ./alembic
COPY alembic.ini .
COPY .env .

EXPOSE 8000

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
