name: Tables_Booking_Workflow

on:
  push:
    branches:
      - develop

jobs:
# Сообщение о коммите в ветку
  send-telegram-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_KOM_AE }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🎉 Новый коммит в репозитории ${{ github.repository }}!
            - Автор: ${{ github.actor }}
            - Бранч: ${{ github.ref_name }}
            - Сообщение: ${{ github.event.head_commit.message }}
            - Ссылка: ${{ github.server_url }}/${{ github.repository }}/commit/${{github.sha}}

# # Запуск тестов бэкэнда
  backend_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run tests with docker-compose
        run: |
          docker compose -f infra/docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from test-runner

      - name: Copy test.log from container
        if: always()
        run: |
          docker cp $(docker ps -aqf "name=test-runner"):/app/test.log ./test.log || echo "No test.log found"

      - name: Upload test log artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-log
          path: ./test.log
          retention-days: 7

      - name: Clean up
        if: always()
        run: docker compose -f infra/docker-compose.test.yml down -v

      - name: Send message
        if: success() || failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_KOM_AE }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Статус выполнения тестов:
            - Задача: ${{ github.job }}
            - Статус: ${{ job.status }}

# Собрать образ бэкэнда и залить на DockerHub
  build_backend_and_push_to_docker_hub:
    name: Push Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker 
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/tables_booking_system:latest
# Отправить сообщение
      - name: Send message
        if: success() || failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_KOM_AE }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Статус выполнения задачи Action:
            - Задача: ${{ github.job }}
            - Статус: ${{ job.status }}
  
# Деплой на сервер
  deploy:
    runs-on: ubuntu-latest
    needs: 
      - build_backend_and_push_to_docker_hub
    steps:
    - name: Checkout repo
      uses: actions/checkout@v5
    - name: Copy docker-compose.production.yml via ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ vars.HOST }}
        username: ${{ vars.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        source: "./infra/docker-compose.production.yml"
        target: "/opt/bron-2/"

    - name: Executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ vars.HOST }}
        username: ${{ vars.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          cd /opt/bron-2/
          # Выполняет pull образов с Docker Hub
          sudo docker compose -f infra/docker-compose.production.yml pull
          # Перезапускает все контейнеры в Docker Compose
          sudo docker compose -f infra/docker-compose.production.yml down
          sudo docker compose -f infra/docker-compose.production.yml up -d

# Отправить сообщение
    - name: Send message
      if: success() || failure()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_KOM_AE }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          Статус выполнения задачи Action:
          - Задача: ${{ github.job }}
          - Статус: ${{ job.status }}